name: Add offer (OpenLine Exchange)

on:
  workflow_dispatch:
    inputs:
      receipt_url:
        description: "URL to producer's receipt.latest.json"
        required: true
      price_usd:
        description: "Listing price in USD (number)"
        required: true
      royalty_bps:
        description: "Creator royalty in basis points (0-10000)"
        required: true
        default: "0"

permissions:
  contents: write

concurrency:
  group: add-offer
  cancel-in-progress: true

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jsonschema requests pynacl

      - name: Add offer
        env:
          RECEIPT_URL: ${{ github.event.inputs.receipt_url }}
          PRICE_USD: ${{ github.event.inputs.price_usd }}
          ROYALTY_BPS: ${{ github.event.inputs.royalty_bps }}
        run: |
          python scripts/add_offer.py \
            --url "$RECEIPT_URL" --price "$PRICE_USD" --royalty "$ROYALTY_BPS"

      - name: Commit offer + index
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/offers/*.json docs/offers/index.json
          git diff --staged --quiet && echo "no changes" || git commit -m "exchange: add offer"
          git push
